# Usando o pacote Numpy

#### O Numpy trabalha basicamente com duas estruturas de dados: `Listas` e `Matrizes`.

## 1. Manipulando ***LISTAS***

In [26]:
# importando o pacote externo
import numpy as np

### Realizando Operações Básicas

In [27]:
# Lista de exemplo
lista_exemplo = [1, 2, 3, 4, 5]

# Criando um array unidimensional
array_a = np.array(lista_exemplo)

array_a

array([1, 2, 3, 4, 5])

In [28]:
# Acessar o primeiro elemento
primeiro = array_a[0]
print("Primeiro item:", primeiro)

# Acessar o último elemento
ultimo = array_a[-1]
print("Último item:", ultimo)

Primeiro item: 1
Último item: 5


In [29]:
# Acessar o segundo e terceiro elementos
segmento = array_a[1:3]

print("Array A:", array_a)
print("Intervalo:", segmento)

Array A: [1 2 3 4 5]
Intervalo: [2 3]


In [30]:
# Adicionando novos elementos
array_maior = np.append(array_a, [16, 17, 18])

print("Array A:", array_a)
print("Novo array maior:", array_maior)
print("A função 'append' inclui valores.")

Array A: [1 2 3 4 5]
Novo array maior: [ 1  2  3  4  5 16 17 18]
A função 'append' inclui valores.


In [31]:
# Excluindo elementos
array_menor = np.delete(array_a, [2, 4])

print("Array A:", array_a)
print("Novo array menor:", array_menor)
print("Cuidado: a função 'delete' exclui posições e não valores")

Array A: [1 2 3 4 5]
Novo array menor: [1 2 4]
Cuidado: a função 'delete' exclui posições e não valores


### Filtrando e transformando os elementos

In [32]:
# Multiplicando arrays por valores absolutos ("escalares")
array_duplicado = array_a * 2

print("Array A:", array_a)
print("Array duplicado:", array_duplicado)

Array A: [1 2 3 4 5]
Array duplicado: [ 2  4  6  8 10]


In [33]:
# Filtrando valores maiores que 3
filtro = array_a > 3
array_filtrado = array_a[filtro]

print(array_filtrado)

[4 5]


In [34]:
# Filtrando valores pares
pares = array_a % 2 == 0
array_pares = array_a[pares]

print(array_pares)

[2 4]


### Operações entre dois arrays

In [35]:
# Criando outro array unidimensional
array_b = np.array([6, 7, 8, 9, 10])

In [36]:
# Calculando a soma entre arrays
soma = np.add(array_a, array_b)

print(array_a)
print(array_b)
print('-' * 17)
print(soma)

[1 2 3 4 5]
[ 6  7  8  9 10]
-----------------
[ 7  9 11 13 15]


In [37]:
# Calculando o produto escalar entre arrays
produto_escalar = np.dot(array_a, array_b)

print(produto_escalar)

130


In [38]:
# Concatenando arrays
resultado = np.concatenate((array_a, array_b))

print(resultado)

[ 1  2  3  4  5  6  7  8  9 10]


## 2. Manipulando ***MATRIZES***

#### O ***Numpy*** é usado, principalmente, para fazer cálculos com **MATRIZES**, que são listas multidimensionais (listas de outras listas):

In [39]:
# Criar uma matriz bidimensional com valores aleatórios
matriz = np.array([[1, 2, 3], [4, 5, 6]])

print(matriz)

[[1 2 3]
 [4 5 6]]


In [40]:
# Acessar o primeiro elemento da primeira linha
primeiro_elemento_primeira_linha = matriz[0, 0]
print("1º elemento da 1ª linha:", primeiro_elemento_primeira_linha)

# Acessar a segunda linha
segunda_linha = matriz[1, :]
print("2ª linha:", segunda_linha)

# Acessar a terceira coluna
terceira_coluna = matriz[:, 2]
print("3ª coluna:", terceira_coluna)

1º elemento da 1ª linha: 1
2ª linha: [4 5 6]
3ª coluna: [3 6]


In [41]:
# Calcular a transposta da matriz
matriz_transposta = np.transpose(matriz)

print(matriz_transposta)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
# Calcular a soma de todos os elementos da matriz
soma_total = np.sum(matriz)

soma_total

21

In [43]:
# Encontrar o valor máximo da matriz
valor_maximo = np.amax(matriz)

valor_maximo

6

In [44]:
# Filtrar as linhas que tenham valores maiores que 5
filtro = np.any(matriz > 5, axis=1)
matriz_filtrada = matriz[filtro, :]

print("Matriz original:\n", matriz)
print("\nMatriz filtrada:\n", matriz_filtrada)

Matriz original:
 [[1 2 3]
 [4 5 6]]

Matriz filtrada:
 [[4 5 6]]


In [45]:
# Criar uma matriz bidimensional com valores aleatórios
matriz_aleatoria = np.random.randint(10, size=(3, 3))

print(matriz_aleatoria)

[[5 2 6]
 [0 8 9]
 [2 0 7]]
